#!/usr/bin/env bash
#
# RDD Init Command
# Initialize a new RDD project
#
# Usage: rdd init [NAME] [--interactive]
#

set -euo pipefail

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

# RDD init function
rdd_init() {
    local project_name=""
    local project_dir=""
    local interactive=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --interactive|-i)
                interactive=true
                shift
                ;;
            --help|-h)
                show_init_help
                exit 0
                ;;
            -*)
                log_error "Unknown option: $1"
                echo "Use 'rdd init --help' for usage"
                exit 1
                ;;
            *)
                if [[ -z "${project_name}" ]]; then
                    project_name="$1"
                fi
                shift
                ;;
        esac
    done

    # If interactive mode, use interactive wizard
    if [[ "${interactive}" == "true" ]]; then
        source "${SCRIPT_DIR}/init-interactive.sh"
        interactive_init
        return
    fi

    # Determine project directory
    if [[ -n "${project_name}" ]]; then
        project_dir="${project_name}"
        mkdir -p "${project_dir}"
    else
        project_dir="$(pwd)"
        project_name="$(basename "${project_dir}")"
    fi

    log_step "Initializing RDD project: ${project_name}"

    # Create directory structure
    log_info "Creating directory structure..."
    create_dirs "${project_dir}"

    # Create configuration files
    log_info "Creating configuration files..."
    create_config "${project_dir}" "${project_name}"

    # Create documentation
    log_info "Creating documentation..."
    create_docs "${project_dir}" "${project_name}"

    # Create entry points
    log_info "Creating entry points..."
    create_entry_points "${project_dir}" "${project_name}"

    log_success "RDD project initialized at ${project_dir}"
    echo ""
    echo "Next steps:"
    echo "  1. Edit docs/01-charter.md with your project vision"
    echo "  2. Edit docs/stages/stage-roadmap.md to plan your stages"
    echo "  3. Run 'task doctor' to verify setup"
    echo "  4. Open Claude Code and use /rdd-stage-auto to start"
}

show_init_help() {
    cat << 'EOF'
RDD Init - Initialize a new RDD project

Usage:
    rdd init [NAME] [OPTIONS]

Options:
    --interactive, -i    Use interactive wizard
    --help, -h           Show this help message

Arguments:
    NAME                 Project name (optional, uses current directory if not specified)

Examples:
    rdd init                    Initialize in current directory
    rdd init my-project         Create new project in my-project/
    rdd init --interactive      Use interactive wizard
EOF
}

create_config() {
    local dir="$1"
    local name="$2"
    local date
    date=$(date +%Y-%m-%d)

    mkdir -p "${dir}/.rdd/config"

    cat > "${dir}/.rdd/config.yml" << EOF
# RDD Configuration
# Generated by RDD Framework

version: "1.0.0"
project:
  name: "${name}"
  description: "A project using RDD Framework"

# Stage settings
stage:
  min_coverage: 20
  max_failures: 3
  tech_debt_threshold: 3

# Gate settings
gates:
  design_required: true
  review_required: true
  e2e_required: true
  docs_required: true

# Hook settings
hooks:
  enabled: false
  config_file: ".rdd/config/hooks.yml"
EOF

    echo "1.0.0" > "${dir}/.rdd/VERSION"
}

create_docs() {
    local dir="$1"
    local name="$2"
    local date
    date=$(date +%Y-%m-%d)

    mkdir -p "${dir}/docs/stages"

    cat > "${dir}/docs/01-charter.md" << EOF
# Project Charter

**Project**: ${name}
**Created**: ${date}

## Vision

[Describe your project vision here]

## Goals

1. [Goal 1]
2. [Goal 2]
3. [Goal 3]

## Non-Goals

1. [What this project will NOT do]

## Success Criteria

- [ ] [Measurable success criterion 1]
- [ ] [Measurable success criterion 2]
EOF

    cat > "${dir}/docs/11-next-steps.md" << EOF
# Next Steps

**Last Updated**: ${date}

## Current Status

**Stage**: 0 (Initialization)

## Immediate Actions

- [ ] Define project vision in docs/01-charter.md
- [ ] Create roadmap in docs/stages/stage-roadmap.md
- [ ] Set up development environment
EOF

    cat > "${dir}/CHANGELOG.md" << EOF
# Changelog

## [Unreleased]

### Added
- Initial project setup
EOF
}

create_entry_points() {
    local dir="$1"
    local name="$2"

    cat > "${dir}/AGENTS.md" << EOF
# Agent Entry Point

> AI Agent entry point for ${name}

## Quick Start

1. Read docs/01-charter.md for project vision
2. Read docs/11-next-steps.md for current status
3. Use /rdd-stage-auto to start development

## RDD Commands

| Command | Purpose |
|---------|---------|
| /rdd-init | Initialize project |
| /rdd-stage-auto | Execute stage |
| /rdd-knowledge | Manage knowledge |
EOF

    cat > "${dir}/CLAUDE.md" << EOF
# Claude Code Entry Point

> Quick reference for Claude Code

## Project: ${name}

## Quick Commands

\`\`\`bash
task doctor      # Check project health
task test        # Run tests
task status      # Show status
\`\`\`

## RDD Skills

| Skill | Purpose |
|-------|---------|
| /rdd-stage-auto | Execute stage with gates |
| /rdd-knowledge | Record decisions |
EOF

    cat > "${dir}/Taskfile.yml" << EOF
version: '3'

tasks:
  doctor:
    desc: Run project health check
    cmds:
      - echo "Project health check"
      - echo "All checks passed"

  test:
    desc: Run tests
    cmds:
      - echo "Running tests..."

  status:
    desc: Show project status
    cmds:
      - echo "Project status"
EOF

    cat > "${dir}/.gitignore" << EOF
# RDD
.rdd/cache/

# OS
.DS_Store
Thumbs.db

# IDE
.idea/
.vscode/
*.swp

# Logs
*.log

# Environment
.env
.env.local
EOF
}

# Run if called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    rdd_init "$@"
fi
