#!/bin/bash
#
# RDD Version Management Script
# Manages semantic versioning and compatibility for RDD Framework
#
# Usage: version.sh [command] [options]
#
# Commands:
#   current       - Show current version
#   check         - Check compatibility with a version
#   compare       - Compare two versions
#   bump          - Bump version (major/minor/patch)
#   validate      - Validate version string
#   matrix        - Show compatibility matrix
#   history       - Show version history
#
# Options:
#   --version V   - Specify version to check/compare
#   --format FMT  - Output format: text, json (default: text)
#

set -euo pipefail

# Configuration
RDD_DIR="${RDD_DIR:-$(dirname "$0")/..}"
VERSION_FILE="${RDD_DIR}/VERSION"
HISTORY_FILE="${RDD_DIR}/VERSION_HISTORY"

# Current version (will be read from VERSION file)
CURRENT_VERSION="${CURRENT_VERSION:-}"
COMPAT_MIN="${COMPAT_MIN:-0.9.0}"
COMPAT_MAX="${COMPAT_MAX:-2.0.0}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

#######################################
# Logging functions
#######################################

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*" >&2
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_debug() {
    if [[ "${VERBOSE:-false}" == "true" ]]; then
        echo -e "${BLUE}[DEBUG]${NC} $*" >&2
    fi
}

#######################################
# Version file operations
#######################################

# Read version from VERSION file
read_version_file() {
    if [[ -f "$VERSION_FILE" ]]; then
        # Source the version file
        # shellcheck source=/dev/null
        source "$VERSION_FILE"
        CURRENT_VERSION="${VERSION:-0.0.0}"
        COMPAT_MIN="${COMPAT_MIN:-0.0.0}"
        COMPAT_MAX="${COMPAT_MAX:-99.99.99}"
    else
        CURRENT_VERSION="0.0.0"
        log_warn "VERSION file not found, using default: $CURRENT_VERSION"
    fi
}

# Write version to VERSION file
write_version_file() {
    local version="$1"
    local compat_min="${2:-$COMPAT_MIN}"
    local compat_max="${3:-$COMPAT_MAX}"

    cat > "$VERSION_FILE" <<EOF
# RDD Framework Version
# This file is auto-generated by version.sh
# Do not edit manually

VERSION=${version}
COMPAT_MIN=${compat_min}
COMPAT_MAX=${compat_max}

# Version history is tracked in VERSION_HISTORY
EOF

    log_info "Version file updated: $VERSION_FILE"
}

# Add entry to version history
add_history_entry() {
    local old_version="$1"
    local new_version="$2"
    local change_type="$3"
    local description="${4:-}"
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Create history file if not exists
    touch "$HISTORY_FILE"

    # Add entry
    cat >> "$HISTORY_FILE" <<EOF
# ${timestamp}
# ${change_type}: ${old_version} -> ${new_version}
# ${description}

EOF

    log_debug "History entry added"
}

#######################################
# Version parsing and comparison
#######################################

# Parse version into components
parse_version() {
    local version="$1"

    # Remove 'v' prefix if present
    version="${version#v}"

    # Validate format
    if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$ ]]; then
        return 1
    fi

    # Extract components
    local major minor patch prerelease
    IFS='-' read -r base prerelease <<< "$version"
    IFS='.' read -r major minor patch <<< "$base"

    echo "${major:-0} ${minor:-0} ${patch:-0} ${prerelease:-}"
}

# Compare two versions
# Returns: 0 if equal, 1 if first > second, 2 if first < second
compare_versions() {
    local v1="$1"
    local v2="$2"

    # Parse versions
    local v1_major v1_minor v1_patch v1_pre
    local v2_major v2_minor v2_patch v2_pre

    read -r v1_major v1_minor v1_patch v1_pre <<< "$(parse_version "$v1")"
    read -r v2_major v2_minor v2_patch v2_pre <<< "$(parse_version "$v2")"

    # Compare major
    if [[ $v1_major -gt $v2_major ]]; then
        return 1
    elif [[ $v1_major -lt $v2_major ]]; then
        return 2
    fi

    # Compare minor
    if [[ $v1_minor -gt $v2_minor ]]; then
        return 1
    elif [[ $v1_minor -lt $v2_minor ]]; then
        return 2
    fi

    # Compare patch
    if [[ $v1_patch -gt $v2_patch ]]; then
        return 1
    elif [[ $v1_patch -lt $v2_patch ]]; then
        return 2
    fi

    # Compare prerelease (no prerelease > prerelease)
    if [[ -z "$v1_pre" && -n "$v2_pre" ]]; then
        return 1
    elif [[ -n "$v1_pre" && -z "$v2_pre" ]]; then
        return 2
    elif [[ -n "$v1_pre" && -n "$v2_pre" ]]; then
        if [[ "$v1_pre" > "$v2_pre" ]]; then
            return 1
        elif [[ "$v1_pre" < "$v2_pre" ]]; then
            return 2
        fi
    fi

    # Equal
    return 0
}

# Check if version is within compatibility range
check_compatibility() {
    local version="$1"
    local compat_min="$2"
    local compat_max="$3"

    log_debug "Checking compatibility: $version (min: $compat_min, max: $compat_max)"

    # Check minimum
    local result
    compare_versions "$version" "$compat_min" || result=$?
    if [[ ${result:-0} -eq 2 ]]; then
        log_error "Version $version is below minimum $compat_min"
        return 1
    fi

    # Check maximum
    result=0
    compare_versions "$version" "$compat_max" || result=$?
    if [[ $result -eq 1 ]]; then
        log_error "Version $version is above maximum $compat_max"
        return 1
    fi

    log_info "Version $version is compatible (range: $compat_min - $compat_max)"
    return 0
}

# Validate version string
validate_version() {
    local version="$1"

    # Remove 'v' prefix if present
    version="${version#v}"

    # Check format
    if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$ ]]; then
        return 0
    else
        return 1
    fi
}

#######################################
# Version bump operations
#######################################

# Bump version
bump_version() {
    local bump_type="$1"
    local current="$2"

    local major minor patch prerelease
    read -r major minor patch prerelease <<< "$(parse_version "$current")"

    case "$bump_type" in
        major)
            major=$((major + 1))
            minor=0
            patch=0
            ;;
        minor)
            minor=$((minor + 1))
            patch=0
            ;;
        patch)
            patch=$((patch + 1))
            ;;
        prerelease)
            # Increment prerelease or start new one
            if [[ -n "$prerelease" ]]; then
                if [[ "$prerelease" =~ ^([a-zA-Z]+)([0-9]+)$ ]]; then
                    local pre_type="${BASH_REMATCH[1]}"
                    local pre_num="${BASH_REMATCH[2]}"
                    prerelease="${pre_type}$((pre_num + 1))"
                else
                    prerelease="${prerelease}.1"
                fi
            else
                prerelease="alpha.1"
                patch=$((patch + 1))
            fi
            ;;
        *)
            log_error "Unknown bump type: $bump_type"
            return 1
            ;;
    esac

    if [[ -n "$prerelease" ]]; then
        echo "${major}.${minor}.${patch}-${prerelease}"
    else
        echo "${major}.${minor}.${patch}"
    fi
}

#######################################
# Commands
#######################################

# Show current version
cmd_current() {
    read_version_file

    local format="${OUTPUT_FORMAT:-text}"

    if [[ "$format" == "json" ]]; then
        cat <<EOF
{
  "version": "${CURRENT_VERSION}",
  "compat_min": "${COMPAT_MIN}",
  "compat_max": "${COMPAT_MAX}"
}
EOF
    else
        log_info "Current version: $CURRENT_VERSION"
        echo "  Compatibility: $COMPAT_MIN - $COMPAT_MAX"
    fi
}

# Check compatibility
cmd_check() {
    local version="${CHECK_VERSION:-}"

    if [[ -z "$version" ]]; then
        log_error "Version not specified. Use --version V"
        return 1
    fi

    if ! validate_version "$version"; then
        log_error "Invalid version format: $version"
        return 1
    fi

    read_version_file

    check_compatibility "$version" "$COMPAT_MIN" "$COMPAT_MAX"
}

# Compare two versions
cmd_compare() {
    local v1="${VERSION1:-}"
    local v2="${VERSION2:-}"

    if [[ -z "$v1" || -z "$v2" ]]; then
        log_error "Two versions required. Use --v1 and --v2"
        return 1
    fi

    if ! validate_version "$v1"; then
        log_error "Invalid version format: $v1"
        return 1
    fi

    if ! validate_version "$v2"; then
        log_error "Invalid version format: $v2"
        return 1
    fi

    compare_versions "$v1" "$v2"
    local result=$?

    case $result in
        0)
            log_info "$v1 == $v2"
            ;;
        1)
            log_info "$v1 > $v2"
            ;;
        2)
            log_info "$v1 < $v2"
            ;;
    esac

    return 0
}

# Bump version
cmd_bump() {
    local bump_type="${BUMP_TYPE:-patch}"

    if [[ ! "$bump_type" =~ ^(major|minor|patch|prerelease)$ ]]; then
        log_error "Invalid bump type: $bump_type (use: major, minor, patch, prerelease)"
        return 1
    fi

    read_version_file

    local old_version="$CURRENT_VERSION"
    local new_version
    new_version=$(bump_version "$bump_type" "$CURRENT_VERSION")

    log_info "Bumping version: $old_version -> $new_version"

    # Update VERSION file
    write_version_file "$new_version" "$COMPAT_MIN" "$COMPAT_MAX"

    # Add to history
    add_history_entry "$old_version" "$new_version" "$bump_type" "Version bump"

    log_info "Version updated successfully"
}

# Validate version
cmd_validate() {
    local version="${VALIDATE_VERSION:-}"

    if [[ -z "$version" ]]; then
        log_error "Version not specified. Use --version V"
        return 1
    fi

    if validate_version "$version"; then
        log_info "Valid version: $version"

        # Parse and show components
        local major minor patch prerelease
        read -r major minor patch prerelease <<< "$(parse_version "$version")"

        echo "  Major: $major"
        echo "  Minor: $minor"
        echo "  Patch: $patch"
        if [[ -n "$prerelease" ]]; then
            echo "  Prerelease: $prerelease"
        fi
        return 0
    else
        log_error "Invalid version format: $version"
        echo "  Expected format: MAJOR.MINOR.PATCH[-prerelease]"
        echo "  Example: 1.0.0 or 1.0.0-alpha.1"
        return 1
    fi
}

# Show compatibility matrix
cmd_matrix() {
    read_version_file

    local format="${OUTPUT_FORMAT:-text}"

    if [[ "$format" == "json" ]]; then
        cat <<EOF
{
  "current": "${CURRENT_VERSION}",
  "compatibility": {
    "min": "${COMPAT_MIN}",
    "max": "${COMPAT_MAX}"
  },
  "matrix": [
    {"version": "0.9.0", "status": "deprecated"},
    {"version": "1.0.0", "status": "stable"},
    {"version": "1.1.0", "status": "stable"},
    {"version": "1.2.0", "status": "current"},
    {"version": "2.0.0", "status": "planned"}
  ]
}
EOF
    else
        log_info "Compatibility Matrix"
        echo ""
        echo "Current Version: $CURRENT_VERSION"
        echo "Compatible Range: $COMPAT_MIN - $COMPAT_MAX"
        echo ""
        echo "Version Matrix:"
        echo "  0.9.0  - deprecated (migration required)"
        echo "  1.0.0  - stable"
        echo "  1.1.0  - stable"
        echo "  1.2.0  - current"
        echo "  2.0.0  - planned (breaking changes)"
    fi
}

# Show version history
cmd_history() {
    if [[ ! -f "$HISTORY_FILE" ]]; then
        log_info "No version history found"
        return 0
    fi

    log_info "Version History"
    echo ""
    cat "$HISTORY_FILE"
}

#######################################
# Show usage
#######################################

show_usage() {
    cat << EOF
RDD Version Management Script

Usage: version.sh [command] [options]

Commands:
  current       Show current version
  check         Check compatibility with a version
  compare       Compare two versions
  bump          Bump version (major/minor/patch)
  validate      Validate version string
  matrix        Show compatibility matrix
  history       Show version history

Options:
  --version V       Version to check/validate
  --v1 V            First version for comparison
  --v2 V            Second version for comparison
  --type T          Bump type: major, minor, patch, prerelease
  --format FMT      Output format: text, json (default: text)
  -v, --verbose     Enable verbose output
  -h, --help        Show this help message

Version Format:
  MAJOR.MINOR.PATCH[-PRERELEASE]

  Examples:
    1.0.0           Stable release
    1.0.0-alpha.1   Alpha prerelease
    1.0.0-beta.2    Beta prerelease
    1.0.0-rc.1      Release candidate

Semantic Versioning Rules:
  MAJOR - Breaking changes
  MINOR - New features, backward compatible
  PATCH - Bug fixes, backward compatible

Examples:
  # Show current version
  version.sh current

  # Check compatibility
  version.sh check --version 1.0.0

  # Compare two versions
  version.sh compare --v1 1.0.0 --v2 1.1.0

  # Bump patch version
  version.sh bump --type patch

  # Validate version string
  version.sh validate --version 1.0.0-alpha.1

  # Show compatibility matrix (JSON)
  version.sh matrix --format json

Environment Variables:
  RDD_DIR           RDD configuration directory
  CURRENT_VERSION   Override current version
  COMPAT_MIN        Minimum compatible version
  COMPAT_MAX        Maximum compatible version

Files:
  .rdd/VERSION          Current version file
  .rdd/VERSION_HISTORY  Version history log

EOF
}

#######################################
# Parse arguments
#######################################

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --version)
                CHECK_VERSION="$2"
                VALIDATE_VERSION="$2"
                shift 2
                ;;
            --v1)
                VERSION1="$2"
                shift 2
                ;;
            --v2)
                VERSION2="$2"
                shift 2
                ;;
            --type)
                BUMP_TYPE="$2"
                shift 2
                ;;
            --format)
                OUTPUT_FORMAT="$2"
                shift 2
                ;;
            -v|--verbose)
                VERBOSE=true
                shift
                ;;
            -h|--help|help)
                show_usage
                exit 0
                ;;
            *)
                shift
                ;;
        esac
    done
}

#######################################
# Main entry point
#######################################

main() {
    if [[ $# -lt 1 ]]; then
        show_usage
        exit 1
    fi

    local command="$1"
    shift
    parse_args "$@"

    case "$command" in
        current)
            cmd_current
            ;;
        check)
            cmd_check
            ;;
        compare)
            cmd_compare
            ;;
        bump)
            cmd_bump
            ;;
        validate)
            cmd_validate
            ;;
        matrix)
            cmd_matrix
            ;;
        history)
            cmd_history
            ;;
        -h|--help|help)
            show_usage
            exit 0
            ;;
        *)
            log_error "Unknown command: $command"
            show_usage
            exit 1
            ;;
    esac
}

# Only run main if script is executed directly
if [[ "${BASH_SOURCE[0]:-$0}" == "${0}" ]]; then
    main "$@"
fi
